### ISSUE TITLE
Static analysis: Utilities for data processing and types conversions

### ISSUE THREAD

**Issue by Karm** [Karm/PA193_SixEleven_parser_critique#4]
Project contains several implementations of hex/bytes conversions. The task is to verify that there are unit tests for these data processing methods and that they are correct and sound and robust against malevolent output.

# Call to action
 * Inspect and report

**Comment by jkremlacek** [comment]
Conversions are not tested at all. Only single valid block and single invalid block are tested. Nothing to do here...

**Comment by RichardKalinec** [comment]
Indeed, there are following methods in Utils.java that perform some kind of conversion:
```java
public int hexToInt(String hex){ // Converts Hex to Int Value
public long hexToLong(String hex){  // Converts Hex to Long Value
public String reverseHex(String hex)  // Converts Hex Values From Reverse Order
public String timestampToDate(String hex){  // Convert Hex Value To TimeStamp
```
However, none of them is directly called in the one and only test method. As a result, the test calls SixElevenBlock's constructor, Parse_Hex() and assertion over ifValid(), but it cannot be easily known if the potential discrepancies and problems are caused in these methods, or in the conversion methods listed above called from these methods.
