### ISSUE TITLE
Static analysis: FindBugs or any alternative as a part of CI (Jenkins, Circle CI, Travis...)

### ISSUE THREAD

**Issue by Karm** [Karm/PA193_SixEleven_parser_critique#7]
Static analysis should run alongside unit tests with each proposed pull request. The task would be to present a solution where this could be achieved either with Travis CI or with Dockerized FindBugs in Circle CI.
# Call to action
 * inspect project's Travis ci for static analysis tools
 * if necessary, establish CI with FindBugs
   * Dockerize FindBugs for Circle CI if Travis cannot handle it

**Comment by RichardKalinec** [comment]
That would be nice to have, but there is no time for that, I managed to use FindBugs and PMD without that, so this issue is closed, at least for now. I will create the same issue in the original repository to suggest this desirable option to the authors.
